version: "3.7"
services:
  # Uncomment the following lines if you want to use filebeat for log ingestion.
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.9.3
  #   volumes:
  #     - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - logs:/var/log/raymon

  ingest_retinopathy:
    build:
      context: .
      args:
        PIP_INDEX_URL: https://${FURY_DEPLOY_AUTH}:@pypi.fury.io/raymon/
        PIP_TRUSTED_HOST: "pypi.orgfiles.pythonhosted.org download.pytorch.org"
        PIP_EXTRA_INDEX_URL: https://pypi.org/simple/
    image: eu.gcr.io/dev-infra-282913/ingest_retinopathy:21
    volumes:
      - logs:/var/log/raymon
      # We should really use secrets for this, but this is easier to run since it allows to run using docker-compose. See comments below for secrets.
      - ./m2mcreds-retinopathy.json:/run/secrets/m2mcreds-retinopathy.json
    environment:
      RAYMON_ENDPOINT: "https://api.raymon.ai/v0"
      PROJECT_ID: 6b71c2eb-5800-4af8-b7ec-ff26db0fa137
      RAYMON_CLIENT_SECRET_FILE: /run/secrets/m2mcreds-retinopathy.json
      RAYMON_N_RAYS: 10
      LOG_PATH: "/var/log/raymon/"
#     secrets:
#       - m2mcreds-retinopathy.json

# secrets:
#   m2mcreds-retinopathy.json:
#     file: m2mcreds-retinopathy.json

volumes:
  logs: null
